name: SonarQube Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.host.url=https://your-sonarqube-server \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Send webhook
        run: |
          curl -X POST https://your-webhook-endpoint \
          -H 'Content-Type: application/json' \
          -H 'X-SONARQUBE-TOKEN: your_webhook_secret' \
          -d '{"projectKey":"your_project_key","status":"completed"}'
